---
- name: Configure Nginx Backend
  hosts: backends
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Deploy Hello World page
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head><title>Nginx Backend</title></head>
          <body>
            <h1>Hello from Nginx!</h1>
            <p>Server: {{ inventory_hostname }}</p>
          </body>
          </html>
        mode: '0644'

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes
